export const FETCH_ORDINALS = "FETCH_ORDINALS";
export const FETCH_ORDINALS_SUCCESS = "FETCH_ORDINALS_SUCCESS";
export const FETCH_ORDINALS_FAILURE = "FETCH_ORDINALS_FAILURE";

export const FETCH_ORDINAL_DETAIL = "FETCH_ORDINAL_DETAIL";
export const FETCH_ORDINAL_DETAIL_FAILURE = "FETCH_ORDINAL_DETAIL_FAILURE";
export const FETCH_ORDINAL_DETAIL_SUCCESS = "FETCH_ORDINAL_DETAIL_SUCCESS";
export const CLEAR_ORDINALS = "CLEAR_ORDINALS";

